### DISCUSSION TITLE
Move toast in front of modal.

### DISCUSSION THREAD

**Discussion by MikeBrownCygnia** [Blazored/Toast#128] [Q&A]
Hi Chris, 

I am using Toast and Modal together, however when I launch a toast from a click within a modal, the toast appears behind the transparent overlay. Can I move this in front of it?

Kind thanks, Michael

![image](https://user-images.githubusercontent.com/88136063/129914505-85d27771-678a-41e2-890f-d68413a38294.png)

**Comment by chrissainty** [comment]
I think you can fix this by applying a higher z-index to the toast. This is the class you need to override:

```css 
﻿.blazored-toast-container {
   z-index: 1; //<-- set this to as higher number as you need to make it the top element.
}
```
