### ISSUE TITLE
[Bug] Long URL overflows

### ISSUE THREAD

**Issue by HmmRfa** [Blazored/Toast#133]
**Describe the bug**
When displaying a long URL in the toast the text overflows the box
![without_text_wrap](https://user-images.githubusercontent.com/10084907/133417162-db45aacb-aab8-4fba-86ae-5a315646b5a5.PNG)

**Reproduce**
Show a toast with long URL (e.g. https://github.com/Blazored/Toast/issues/with/some/really/really_long_url_that_is_really_long)

**Expected behavior**
The URL should be broken

![with_text_wrap](https://user-images.githubusercontent.com/10084907/133417166-71862693-121e-4e6a-89ec-43e9f5bdad40.PNG)

**Possible fix**
```css
.blazored-toast-body p {
    overflow-wrap: break-word;
    word-wrap: break-word;
    word-break: break-word;
    -ms-hyphens: auto;
    -moz-hyphens: auto;
    -webkit-hyphens: auto;
    hyphens: auto;
}
```
